
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 144
#define YY_END_OF_BUFFER 145
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[501] =
    {   0,
        0,    0,  145,  143,    2,    1,   97,  121,   98,  140,
      106,  122,  117,  118,  115,  113,  103,  114,  123,  116,
       84,   99,  100,  101,  109,  102,  110,  112,  141,  141,
      141,  141,  141,  141,  141,  141,  104,  105,  108,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  119,
      111,  120,  107,    2,  134,  142,    0,    5,  142,  139,
      124,    0,    6,    0,  137,  126,  135,  127,   84,  136,
        0,    3,  138,   85,  128,  131,  133,  132,  129,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,

      141,  141,  141,  141,  141,  141,  141,   21,  141,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      141,   35,  141,   38,  141,  141,  141,  141,  141,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      125,    0,    0,    0,    3,   85,  130,  141,  141,  141,
      141,  141,   82,  141,  141,  141,  141,  141,  141,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      141,  141,  141,  141,  141,  141,   32,  141,  141,  141,
      141,  141,  141,  141,   40,  141,  141,  141,  141,  141,

       42,  141,  141,  141,   45,  141,  141,  141,  141,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      141,   62,  141,  141,  141,   64,  141,  141,  141,  141,
      141,    0,    0,    4,  141,   74,  141,  141,   81,  141,
      141,  141,  141,  141,   11,   12,  141,   14,  141,  141,
      141,  141,  141,  141,  141,   23,   24,   25,  141,  141,
      141,  141,  141,   70,  141,  141,   34,  141,  141,  141,
      141,  141,  141,  141,  141,   92,  141,   43,   83,  141,
       46,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      141,  141,  141,   57,  141,  141,  141,   61,  141,  141,

      141,   65,  141,  141,   68,  141,    0,    0,   73,  141,
      141,  141,  141,  141,  141,  141,  141,   10,   13,   15,
       16,  141,  141,  141,  141,  141,  141,  141,   28,   29,
       31,  141,  141,  141,  141,  141,  141,  141,  141,   78,
      141,  141,  141,  141,  141,   71,  141,  141,  141,  141,
      141,  141,   52,  141,   54,  141,  141,   58,  141,  141,
      141,  141,  141,  141,   67,   69,    0,  141,  141,  141,
      141,   86,  141,  141,  141,  141,  141,  141,   20,   22,
       26,  141,  141,  141,  141,  141,  141,   37,  141,  141,
      141,  141,  141,   80,   44,  141,  141,   72,  141,  141,

       50,   51,   53,   55,  141,   59,  141,  141,   63,  141,
      141,  141,  141,  141,  141,  141,  141,  141,    9,  141,
      141,   19,   27,   30,  141,  141,  141,  141,  141,  141,
      141,  141,  141,   47,   48,  141,  141,  141,  141,  141,
      141,   90,  141,   76,  141,  141,  141,    7,  141,   17,
       18,   33,   91,  141,  141,  141,  141,   77,  141,  141,
      141,  141,  141,   88,  141,  141,   66,   93,  141,  141,
        8,  141,  141,  141,   41,  141,   94,   49,   87,  141,
       60,   89,   95,  141,  141,   36,   39,  141,  141,   96,
      141,  141,  141,  141,  141,   56,  141,   79,   75,    0

    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    6,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   27,   30,
       27,   27,   31,   32,   27,   27,   33,   34,   35,   36,
       27,   27,   37,   27,   27,   27,   27,   27,   27,   27,
       38,   39,   40,   41,   27,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   27,   58,   59,   60,   61,   62,   63,   64,
       65,   66,   67,   68,   69,   70,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[71] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    1,    1,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[509] =
    {   0,
        0,    0,  544,  545,  541,  545,  520,   68,  545,  519,
      532,   63,  545,  545,  517,   61,  545,   60,  545,   64,
       61,  545,  545,   63,  516,   65,  545,  545,  479,    0,
      494,  480,  492,  491,  490,  488,  545,  545,  545,   37,
       33,   48,   47,   53,   63,   53,  488,   71,  487,   54,
       50,   70,  482,   73,   83,  472,   81,   93,  476,  545,
      457,  545,  545,  522,  545,  124,  115,  545,  141,  545,
      545,  126,  545,  520,  545,  509,  545,  545,  129,  545,
      509,    0,  545,  502,  545,  545,  545,  545,  496,    0,
      460,  457,  469,  453,  454,  479,  461,  452,  462,  453,

      462,  447,   90,  464,  463,  449,  108,  442,  443,  440,
      458,   96,  446,  443,  441,  438,  439,  439,  433,  432,
      432,    0,  433,   98,  130,  427,  107,  433,  114,  424,
      433,  441,  119,  441,  423,  426,  439,  423,  429,  423,
      120,  440,  129,  419,  430,  119,  123,  424,  413,  426,
      545,  468,  458,  167,    0,  451,  545,  426,  421,  416,
      423,  415,    0,  417,  402,  400,  407,  417,  412,  411,
      412,  397,  395,  121,  392,  410,  405,  407,  403,  394,
      394,  390,  399,  385,  401,  400,    0,  387,  396,  411,
      382,  402,  129,  376,  389,  384,  391,  374,  389,  382,

        0,  381,  382,  377,    0,  373,  373,   97,  129,  371,
      362,  364,  361,  374,  359,  374,  358,  360,  355,  359,
      367,    0,  366,  365,  349,    0,  364,  366,  354,  357,
      352,  392,  174,  545,  338,    0,  347,  161,    0,  357,
      342,  345,  352,  345,    0,    0,  347,    0,  336,  334,
      343,  344,  330,  330,  336,    0,    0,    0,  330,  332,
      340,  332,  324,    0,  323,  329,    0,  318,  334,  321,
      336,  319,  321,  341,  318,  345,  312,    0,    0,  309,
        0,  328,  309,  326,  310,  142,  316,  307,  304,  313,
      304,  317,  311,    0,  296,  300,  298,    0,  300,  308,

      308,    0,  293,  306,    0,  306,  338,  183,    0,  299,
      290,  304,  304,  285,  302,  297,  300,    0,    0,    0,
        0,  286,  292,  286,  292,  291,  276,  290,    0,  281,
        0,  283,  290,  276,  276,  269,  273,  280,  276,    0,
      265,  271,  274,  276,  273,    0,  260,  259,  274,  257,
      272,  260,    0,  270,    0,  264,  254,  252,  260,  259,
      261,  257,  271,  255,    0,    0,  187,  244,  245,  251,
      257,    0,  256,  244,  243,  236,  250,  235,    0,    0,
        0,  235,  228,  236,  232,  254,  243,    0,  244,  245,
      226,  229,  242,    0,    0,  237,  236,    0,  221,  215,

        0,    0,    0,    0,  223,    0,  223,  231,    0,  221,
      228,  221,  208,  230,  225,  218,  209,  208,    0,  221,
      208,    0,    0,    0,  210,  205,  205,  207,  215,  216,
      213,  198,  198,    0,    0,  210,  198,  199,  205,  197,
      205,    0,  204,    0,  184,  204,  205,    0,  187,    0,
        0,    0,    0,  189,  184,  187,  196,    0,  176,  181,
      194,  192,  187,    0,  176,  190,    0,    0,  174,  185,
        0,  175,  172,  183,    0,  172,    0,    0,    0,  162,
        0,    0,    0,  181,  180,    0,    0,  172,  157,    0,
      144,  166,  148,  132,   93,    0,   49,    0,    0,  545,

      204,  207,   91,  210,  213,  216,  219,  222
    } ;

static yyconst flex_int16_t yy_def[509] =
    {   0,
      500,    1,  500,  500,  500,  500,  500,  501,  500,  500,
      500,  502,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  503,  503,
      503,  503,  503,  503,  503,  503,  500,  500,  500,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  500,
      500,  500,  500,  500,  500,  501,  504,  500,  501,  500,
      500,  502,  500,  502,  500,  500,  500,  500,  500,  500,
      505,  506,  500,  500,  500,  500,  500,  500,  500,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,

      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      500,  504,  505,  507,  506,  500,  500,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,

      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  508,  507,  500,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,

      503,  503,  503,  503,  503,  503,  508,  507,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  507,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,

      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,    0,

      500,  500,  500,  500,  500,  500,  500,  500
    } ;

static yyconst flex_uint16_t yy_nxt[616] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   30,   31,   30,
       32,   33,   34,   35,   36,   30,   30,   37,    4,   38,
       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   30,   50,   30,   51,   30,   52,   53,   54,   55,
       56,   57,   58,   30,   59,   30,   60,   61,   62,   63,
       67,   73,   68,   76,   78,   81,   84,   79,   79,   98,
       82,   80,   77,   85,   86,   83,   88,   89,  100,  103,
      101,  129,  107,   90,   99,  130,  104,  102,  119,  127,

      105,   74,  108,  106,  113,  109,   69,  110,  120,  128,
      131,  132,  114,  499,  111,  115,  112,  122,  116,   68,
      117,  136,  146,  118,  123,  124,   67,  133,   68,  125,
      134,  141,  137,  138,   73,  139,  147,  140,  142,  498,
      143,  148,  149,  500,   84,   67,   79,  144,  170,  171,
      175,  283,  182,  152,  176,  183,  194,  195,  284,  196,
      177,  200,   69,  197,   74,  198,  201,  203,  208,  217,
      220,  225,  227,  204,  209,  228,  226,  218,  233,  250,
      251,  269,  285,  234,  270,  233,  311,  349,  286,  221,
      234,  497,  496,  222,  367,  312,  313,  350,  367,  234,

      495,  494,  493,  234,   66,   66,   66,   72,   72,   72,
       67,   67,   67,  153,  153,  153,  155,  492,  155,  232,
      232,  232,  307,  307,  307,  491,  490,  489,  488,  487,
      486,  485,  484,  483,  482,  481,  480,  479,  478,  477,
      476,  475,  474,  473,  472,  471,  470,  469,  468,  467,
      466,  465,  464,  463,  462,  461,  460,  459,  458,  457,
      456,  455,  454,  453,  452,  451,  450,  449,  448,  447,
      446,  445,  444,  443,  442,  441,  440,  439,  438,  437,
      436,  435,  434,  433,  432,  431,  430,  429,  428,  427,
      426,  425,  424,  423,  422,  421,  420,  419,  418,  417,

      416,  415,  414,  413,  412,  411,  410,  409,  408,  407,
      406,  405,  404,  403,  402,  401,  400,  399,  398,  397,
      396,  395,  394,  393,  392,  391,  390,  389,  388,  387,
      386,  385,  384,  383,  382,  381,  380,  379,  378,  377,
      376,  375,  374,  373,  372,  371,  370,  369,  368,  308,
      366,  365,  364,  363,  362,  361,  360,  359,  358,  357,
      356,  355,  354,  353,  352,  351,  348,  347,  346,  345,
      344,  343,  342,  341,  340,  339,  338,  337,  336,  335,
      334,  333,  332,  331,  330,  329,  328,  327,  326,  325,
      324,  323,  322,  321,  320,  319,  318,  317,  316,  315,

      314,  310,  309,  308,  306,  305,  304,  303,  302,  301,
      300,  299,  298,  297,  296,  295,  294,  293,  292,  291,
      290,  289,  288,  287,  282,  281,  280,  279,  278,  277,
      276,  275,  274,  273,  272,  271,  268,  267,  266,  265,
      264,  263,  262,  261,  260,  259,  258,  257,  256,  255,
      254,  253,  252,  249,  248,  247,  246,  245,  244,  243,
      242,  241,  240,  239,  238,  237,  236,  235,  156,  154,
      500,  231,  230,  229,  224,  223,  219,  216,  215,  214,
      213,  212,  211,  210,  207,  206,  205,  202,  199,  193,
      192,  191,  190,  189,  188,  187,  186,  185,  184,  181,

      180,  179,  178,  174,  173,  172,  169,  168,  167,  166,
      165,  164,  163,  162,  161,  160,  159,  158,  157,  156,
      154,   76,  500,   64,  151,  150,  145,  135,  126,  121,
       97,   96,   95,   94,   93,   92,   91,   87,   75,   71,
       70,   65,   64,  500,    3,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,

      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500
    } ;

static yyconst flex_int16_t yy_chk[616] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        8,   12,    8,   16,   18,   20,   21,   18,   21,   40,
       20,   18,   16,   24,   24,   20,   26,   26,   41,   42,
       41,   51,   43,  503,   40,   51,   42,   41,   46,   50,

       42,   12,   43,   42,   45,   44,    8,   44,   46,   50,
       51,   52,   45,  497,   44,   45,   44,   48,   45,   67,
       45,   54,   57,   45,   48,   48,   66,   52,   66,   48,
       52,   55,   54,   54,   72,   54,   57,   54,   55,  495,
       55,   58,   58,   69,   79,   69,   79,   55,  103,  103,
      107,  208,  112,   67,  107,  112,  124,  124,  208,  125,
      107,  127,   66,  125,   72,  125,  127,  129,  133,  141,
      143,  146,  147,  129,  133,  147,  146,  141,  154,  174,
      174,  193,  209,  154,  193,  233,  238,  286,  209,  143,
      233,  494,  493,  143,  308,  238,  238,  286,  367,  308,

      492,  491,  489,  367,  501,  501,  501,  502,  502,  502,
      504,  504,  504,  505,  505,  505,  506,  488,  506,  507,
      507,  507,  508,  508,  508,  485,  484,  480,  476,  474,
      473,  472,  470,  469,  466,  465,  463,  462,  461,  460,
      459,  457,  456,  455,  454,  449,  447,  446,  445,  443,
      441,  440,  439,  438,  437,  436,  433,  432,  431,  430,
      429,  428,  427,  426,  425,  421,  420,  418,  417,  416,
      415,  414,  413,  412,  411,  410,  408,  407,  405,  400,
      399,  397,  396,  393,  392,  391,  390,  389,  387,  386,
      385,  384,  383,  382,  378,  377,  376,  375,  374,  373,

      371,  370,  369,  368,  364,  363,  362,  361,  360,  359,
      358,  357,  356,  354,  352,  351,  350,  349,  348,  347,
      345,  344,  343,  342,  341,  339,  338,  337,  336,  335,
      334,  333,  332,  330,  328,  327,  326,  325,  324,  323,
      322,  317,  316,  315,  314,  313,  312,  311,  310,  307,
      306,  304,  303,  301,  300,  299,  297,  296,  295,  293,
      292,  291,  290,  289,  288,  287,  285,  284,  283,  282,
      280,  277,  276,  275,  274,  273,  272,  271,  270,  269,
      268,  266,  265,  263,  262,  261,  260,  259,  255,  254,
      253,  252,  251,  250,  249,  247,  244,  243,  242,  241,

      240,  237,  235,  232,  231,  230,  229,  228,  227,  225,
      224,  223,  221,  220,  219,  218,  217,  216,  215,  214,
      213,  212,  211,  210,  207,  206,  204,  203,  202,  200,
      199,  198,  197,  196,  195,  194,  192,  191,  190,  189,
      188,  186,  185,  184,  183,  182,  181,  180,  179,  178,
      177,  176,  175,  173,  172,  171,  170,  169,  168,  167,
      166,  165,  164,  162,  161,  160,  159,  158,  156,  153,
      152,  150,  149,  148,  145,  144,  142,  140,  139,  138,
      137,  136,  135,  134,  132,  131,  130,  128,  126,  123,
      121,  120,  119,  118,  117,  116,  115,  114,  113,  111,

      110,  109,  108,  106,  105,  104,  102,  101,  100,   99,
       98,   97,   96,   95,   94,   93,   92,   91,   89,   84,
       81,   76,   74,   64,   61,   59,   56,   53,   49,   47,
       36,   35,   34,   33,   32,   31,   29,   25,   15,   11,
       10,    7,    5,    3,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,

      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#line 2 "scanner.l"
#define YYSTYPE char *
#include "y.tab.h"
#include "string.h"
int cur_line = 1;
void yyerror(const char *msg);
void unrecognized_char(char c);
void unterminate_string();
#line 777 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 12 "scanner.l"



#line 999 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 501 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 545 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 15 "scanner.l"
{ cur_line++; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 16 "scanner.l"
{/* ignore */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 19 "scanner.l"
{/* ignore */ }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 20 "scanner.l"
{/* ignore */ }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 23 "scanner.l"
{yylval=strdup(yytext); return p77;}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 24 "scanner.l"
{yylval=strdup(yytext); return p77;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 27 "scanner.l"
{ return p0;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 28 "scanner.l"
{ return p1;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 29 "scanner.l"
{ return p2;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 30 "scanner.l"
{ return p3;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 31 "scanner.l"
{ return p4;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 32 "scanner.l"
{ return p5;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 33 "scanner.l"
{ return p6;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 34 "scanner.l"
{ return p7;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 35 "scanner.l"
{ return p8;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 36 "scanner.l"
{ return p9;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 37 "scanner.l"
{ return p10;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 38 "scanner.l"
{ return p11;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 39 "scanner.l"
{ return p12;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 40 "scanner.l"
{ return p13;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 41 "scanner.l"
{ return p14;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 42 "scanner.l"
{ return p15;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 43 "scanner.l"
{ return p16;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 44 "scanner.l"
{ return p17;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 45 "scanner.l"
{ return p18;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 46 "scanner.l"
{ return p19;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 47 "scanner.l"
{ return p20;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 48 "scanner.l"
{ return p21;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 49 "scanner.l"
{ return p22;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 50 "scanner.l"
{ return p23;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 51 "scanner.l"
{ return p24;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 52 "scanner.l"
{ return p25;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 53 "scanner.l"
{ return p26;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 54 "scanner.l"
{ return p27;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 55 "scanner.l"
{ return p28;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 56 "scanner.l"
{ return p29;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 57 "scanner.l"
{ return p30;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 58 "scanner.l"
{ return p31;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 59 "scanner.l"
{ return p32;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 60 "scanner.l"
{ return p33;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 61 "scanner.l"
{ return p34;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 62 "scanner.l"
{ return p35;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 63 "scanner.l"
{ return p36;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 64 "scanner.l"
{ return p37;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 65 "scanner.l"
{ return p38;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 66 "scanner.l"
{ return p39;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 67 "scanner.l"
{ return p40;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 68 "scanner.l"
{ return p41;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 69 "scanner.l"
{ return p42;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 70 "scanner.l"
{ return p43;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 71 "scanner.l"
{ return p44;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 72 "scanner.l"
{ return p45;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 73 "scanner.l"
{ return p46;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 74 "scanner.l"
{ return p47;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 75 "scanner.l"
{ return p48;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 76 "scanner.l"
{ return p49;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 77 "scanner.l"
{ return p50;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 78 "scanner.l"
{ return p51;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 79 "scanner.l"
{ return p52;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 80 "scanner.l"
{ return p53;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 81 "scanner.l"
{ return p54;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 82 "scanner.l"
{ return p55;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 83 "scanner.l"
{ return p56;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 84 "scanner.l"
{ return p57;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 85 "scanner.l"
{ return p58;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 86 "scanner.l"
{ return p59;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 87 "scanner.l"
{ return p60;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 88 "scanner.l"
{ return p61;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 89 "scanner.l"
{ return p62;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 90 "scanner.l"
{ return p130;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 91 "scanner.l"
{ return p131;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 92 "scanner.l"
{ return p132;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 95 "scanner.l"
{ return p63;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 96 "scanner.l"
{ return p64;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 97 "scanner.l"
{ return p65;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 98 "scanner.l"
{ return p66;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 99 "scanner.l"
{ return p67;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 100 "scanner.l"
{ return p68;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 101 "scanner.l"
{ return p69;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 102 "scanner.l"
{ return p70;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 103 "scanner.l"
{ return p71;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 104 "scanner.l"
{ return p72;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 105 "scanner.l"
{ return p73;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 106 "scanner.l"
{yylval=strdup(yytext); return p74;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 107 "scanner.l"
{yylval=strdup(yytext); return p74;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 108 "scanner.l"
{ return p75;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 109 "scanner.l"
{ return p76;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 110 "scanner.l"
{ return p78;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 111 "scanner.l"
{ return p79;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 112 "scanner.l"
{ return p80;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 115 "scanner.l"
{ return p81;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 116 "scanner.l"
{ return p82;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 117 "scanner.l"
{ return p83;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 118 "scanner.l"
{ return p84;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 119 "scanner.l"
{ return p85;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 120 "scanner.l"
{ return p86;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 123 "scanner.l"
{ return p98;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 124 "scanner.l"
{ return p99;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 125 "scanner.l"
{ return p100;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 126 "scanner.l"
{ return p101;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 127 "scanner.l"
{ return p102;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 128 "scanner.l"
{ return p103;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 129 "scanner.l"
{ return p104;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 130 "scanner.l"
{ return p105;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 131 "scanner.l"
{ return p106;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 132 "scanner.l"
{ return p107;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 133 "scanner.l"
{ return p110;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 134 "scanner.l"
{ return p120;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 135 "scanner.l"
{ return p121;}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 136 "scanner.l"
{ return p127;}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 137 "scanner.l"
{ return p128;}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 138 "scanner.l"
{ return p129;}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 141 "scanner.l"
{ return p87;}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 142 "scanner.l"
{ return p88;}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 143 "scanner.l"
{ return p89;}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 144 "scanner.l"
{ return p90;}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 145 "scanner.l"
{ return p91;}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 146 "scanner.l"
{ return p92;}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 147 "scanner.l"
{ return p93;}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 148 "scanner.l"
{ return p94;}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 149 "scanner.l"
{ return p95;}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 150 "scanner.l"
{ return p96;}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 151 "scanner.l"
{ return p97;}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 152 "scanner.l"
{ return p108;}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 153 "scanner.l"
{ return p109;}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 154 "scanner.l"
{ return p111;}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 155 "scanner.l"
{ return p112;}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 156 "scanner.l"
{ return p113;}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 157 "scanner.l"
{ return p114;}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 158 "scanner.l"
{ return p115;}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 159 "scanner.l"
{ return p116;}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 160 "scanner.l"
{ return p117;}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 161 "scanner.l"
{ return p118;}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 162 "scanner.l"
{ return p119;}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 163 "scanner.l"
{ return p122;}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 164 "scanner.l"
{ return p123;}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 165 "scanner.l"
{ return p124;}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 166 "scanner.l"
{ return p125;}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 167 "scanner.l"
{ return p126;}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 168 "scanner.l"
{ return p133;}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 171 "scanner.l"
{ yylval = strdup(yytext); return p200; }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 174 "scanner.l"
{ unterminate_string(); }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 175 "scanner.l"
{ unrecognized_char(yytext[0]); }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 179 "scanner.l"
ECHO;
	YY_BREAK
#line 1780 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 501 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 501 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 500);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 179 "scanner.l"




int yywrap(void) {
    return 1;
}

void unrecognized_char(char c) {
    char buf[32] = "Unrecognized character: ?";
    buf[24] = c;
    yyerror(buf);
}

void unterminate_string() {
    	yyerror("mssing '\"'! ");
}

void yyerror(const char *msg) {
    printf("Error at line %d:\n\t%s\n", cur_line, msg);
    exit(1);
}

